In [17]:
#Pandas2
import pandas as pd
import numpy as np
import openpyxl
import xlrd

In [ ]:
dict={0:["Sudeep", "Aryan", "Shivam", "Jatin", "Anshuman"], 1:[1, 2, 3, 4, 5], 2:[1000.0, 500.0, 200.0, 100.0, 40.0]}
df=pd.DataFrame(dict)
df=df.rename(index={0:"First", 1:"Second", 2:"Third", 3:"Fourth", 4:"Fifth"}, columns={0:"Name", 1:"Rank", 2:"PriceMoney"})
df

In [ ]:
print(df.drop(["Second", "Fourth"], axis=0), end="\n\n")
print(df.drop(["Name", "PriceMoney"], axis=1), end="\n\n")

In [ ]:
df1=df.copy()
df1.drop(["Third"], axis=0, inplace=True)
df1.drop(["Rank"], axis=1, inplace=True)
df1.reset_index(drop=True, inplace=True)
df1

In [ ]:
df2=df.copy()
df2.loc[:, ["PriceMoney"]]=np.NaN
df2.loc[["Fifth"], :]=np.NaN
print(df2.isna(), df2.isnull(), df2.notnull(), sep="\n\n", end="\n\n")
print(df2.fillna(value=0), end="\n\n")
print(df2.dropna(how="any", axis=0), df2.dropna(how="all", axis=0), sep="\n\n", end="\n\n")
print(df2.dropna(how="any", axis=1), df2.dropna(how="all", axis=1), sep="\n\n", end="\n\n")

In [ ]:
df3=df.copy()
df3.loc[["Third"], ["Name"]]="Yash"
df3.loc[["Fifth"], ["Name"]]="Yash"
print(df3["Name"].unique())
print(df3.drop_duplicates(subset=["Name"], keep="first"), end="\n\n")
print(df3.drop_duplicates(subset=["Name"], keep="last"), end="\n\n")
print(df3.drop_duplicates(subset=["Name"], keep=False), end="\n\n")

In [ ]:
df.to_csv("Topper.csv", index=False)
df4=pd.read_csv("Topper.csv")
df4

In [ ]:
df.to_excel("Topper.xlsx", sheet_name="Topper", index=False)
df5=pd.read_excel("Topper.xlsx")
df5